#!/usr/bin/env bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${CYAN}═══════════════════════════════════════${NC}"
echo -e "${CYAN}  CoreIDS Sensor Installer${NC}"
echo -e "${CYAN}═══════════════════════════════════════${NC}"

# ── Root check ─────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo -e "${RED}Error: This script must be run as root (sudo).${NC}"
  exit 1
fi

# ── Parse arguments ─────────────────────────────────────────
DEVICE_ID=""
API_KEY=""
SERVER=""
MODE="full"
IFACE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --device-id=*) DEVICE_ID="${1#*=}" ;;
    --api-key=*)   API_KEY="${1#*=}" ;;
    --server=*)    SERVER="${1#*=}" ;;
    --mode=*)      MODE="${1#*=}" ;;
    --interface=*) IFACE="${1#*=}" ;;
    *) echo -e "${YELLOW}Unknown argument: $1${NC}" ;;
  esac
  shift
done

if [[ -z "$DEVICE_ID" || -z "$API_KEY" || -z "$SERVER" ]]; then
  echo -e "${RED}Error: --device-id, --api-key, and --server are all required.${NC}"
  echo ""
  echo "  Usage: curl -sSL https://your-server/install.sh | sudo bash -s -- \\"
  echo "    --device-id=<id> --api-key=<key> --server=https://your-server"
  echo ""
  exit 1
fi

echo -e "  ${GREEN}Using provided device credentials${NC}"

# ── Instance-specific paths ──────────────────────────────────
# Each device gets its own config, state dir, and systemd instance
CONFIG="/etc/coreids/ids-${DEVICE_ID}.conf"
STATE_DIR="/var/lib/ids/${DEVICE_ID}"
SERVICE_NAME="coreids-${DEVICE_ID}.service"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}"
BIN="/usr/local/bin/coreids-sensor"

mkdir -p /etc/coreids "$STATE_DIR"
cat > "$CONFIG" << CONF
# CoreIDS Sensor Configuration — ${DEVICE_ID}
# Auto-generated by installer
cloud_url         = ${SERVER}
device_id         = ${DEVICE_ID}
api_key           = ${API_KEY}
alert_threshold   = 0.70
block_threshold   = 0.92
escalate_threshold = 0.995
verbose           = true
state_dir         = ${STATE_DIR}
CONF
echo -e "  Config created: ${CONFIG}"

# ── Detect OS ──────────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"
echo -e "  OS:       ${CYAN}${OS} ${ARCH}${NC}"
echo -e "  Mode:     ${CYAN}${MODE}${NC}"

# ── Detect interface (if not provided) ─────────────────────
if [[ -z "$IFACE" ]]; then
  IFACE=$(ip route get 8.8.8.8 2>/dev/null | awk '{print $5; exit}')
  if [[ -n "$IFACE" ]] && ! ip -o link show "$IFACE" | grep -q "state UP"; then
    IFACE=""
  fi
  if [[ -z "$IFACE" ]]; then
    for candidate in eth0 ens3 ens4 enp0s3 enp1s0 wlp2s0 wlan0; do
      if ip link show "$candidate" &>/dev/null && ip -o link show "$candidate" | grep -q "state UP"; then
        IFACE="$candidate"
        break
      fi
    done
  fi
  if [[ -z "$IFACE" ]]; then
    IFACE=$(ip -br link show up 2>/dev/null | awk '$1 != "lo" {print $1; exit}')
  fi
  if [[ -z "$IFACE" ]]; then
    IFACE="eth0"
  fi
fi
echo -e "  Interface: ${CYAN}${IFACE}${NC}"

# ── Install dependencies ───────────────────────────────────
echo ""
echo -e "${CYAN}── Installing dependencies...${NC}"

if command -v apt-get &>/dev/null; then
  apt-get update -qq
  apt-get install -y -qq libcurl4-openssl-dev build-essential cmake 2>/dev/null
elif command -v yum &>/dev/null; then
  yum install -y -q libcurl-devel gcc-c++ make cmake 2>/dev/null
elif command -v apk &>/dev/null; then
  apk add --no-cache libcurl-dev curl-dev g++ make cmake 2>/dev/null
else
  echo -e "${YELLOW}Warning: Could not auto-install dependencies.${NC}"
  echo "  Ensure these are installed: g++, libcurl-dev, make"
fi

# ── Install sensor binary ──────────────────────────────────
BIN="/usr/local/bin/coreids-sensor"

echo ""
echo -e "${CYAN}── Installing CoreIDS sensor...${NC}"

if command -v docker &>/dev/null && [[ "$MODE" == "sensor" ]]; then
  # Docker sensor mode — lighter deployment
  echo -e "  ${GREEN}Docker detected, using container image${NC}"
  docker pull ghcr.io/anomalyco/coreids-sensor:latest 2>/dev/null || {
    echo -e "  ${YELLOW}Image not available, building from source...${NC}"
    TMPDIR=$(mktemp -d)
    if curl -sfL "${SERVER}/download/source.tar.gz" -o "$TMPDIR/source.tar.gz" 2>/dev/null; then
      tar xzf "$TMPDIR/source.tar.gz" -C "$TMPDIR"
    else
      git clone --depth 1 https://github.com/anomalyco/decoderARC.git "$TMPDIR" 2>/dev/null || true
    fi
    cd "$TMPDIR"
    docker build -t coreids-sensor -f Dockerfile . 2>/dev/null || echo "  Docker build failed"
    cd / && rm -rf "$TMPDIR"
  }
  # Create a wrapper script that runs the container
  cat > "$BIN" << 'WRAPPER'
#!/bin/sh
exec docker run --rm --net=host --cap-add=NET_RAW --cap-add=NET_ADMIN \
  -v /etc/coreids:/etc/coreids -v /var/lib/ids:/var/lib/ids \
  coreids-sensor "$@"
WRAPPER
  chmod +x "$BIN"
else
  # Pre-built binary or build from source
  if curl -sfL "${SERVER}/download/coreids-sensor-${ARCH}" -o "$BIN" 2>/dev/null; then
    echo -e "  ${GREEN}Downloaded pre-built binary from server${NC}"
  else
    echo -e "  ${YELLOW}No pre-built binary; building from source tarball...${NC}"
    TMPDIR=$(mktemp -d)
    if curl -sfL "${SERVER}/download/source.tar.gz" -o "$TMPDIR/source.tar.gz" 2>/dev/null; then
      tar xzf "$TMPDIR/source.tar.gz" -C "$TMPDIR"
      g++ -std=c++17 -O2 -I "$TMPDIR/include" "$TMPDIR/tools/ids_production.cpp" -o "$BIN" -lpthread -lcurl
      rm -rf "$TMPDIR"
      echo -e "  ${GREEN}Build complete${NC}"
    elif command -v git &>/dev/null; then
      echo -e "  ${YELLOW}Building from GitHub source...${NC}"
      if git clone --depth 1 https://github.com/anomalyco/decoderARC.git "$TMPDIR" 2>/dev/null; then
        g++ -std=c++17 -O2 -I "$TMPDIR/include" "$TMPDIR/tools/ids_production.cpp" -o "$BIN" -lpthread -lcurl
        rm -rf "$TMPDIR"
        echo -e "  ${GREEN}Build complete${NC}"
      else
        echo -e "${RED}Error: Could not download or build the daemon.${NC}"
        echo "  The server at ${SERVER} was unreachable for source download."
        echo "  Ensure the server is running and accessible, or install git for GitHub fallback."
        exit 1
      fi
    else
      echo -e "${RED}Error: Could not download source from server and git is not installed.${NC}"
      echo "  Install git or ensure ${SERVER} is accessible."
      exit 1
    fi
  fi
fi

chmod +x "$BIN"

# ── Create state directory ─────────────────────────────────
mkdir -p /var/lib/ids

# ─── Create systemd service (per-instance) ─────────────────────
SERVICE_FILE="/etc/systemd/system/coreids-${DEVICE_ID}.service"
cat > "$SERVICE_FILE" << UNIT
[Unit]
Description=CoreIDS Sensor (${DEVICE_ID})
Documentation=https://coreids.dev
After=network.target

[Service]
Type=simple
ExecStart=${BIN} --config ${CONFIG} ${IFACE}
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
CPUQuota=80%
MemoryMax=512M

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable "coreids-${DEVICE_ID}.service"
systemctl restart "coreids-${DEVICE_ID}.service"

# ── Done ───────────────────────────────────────────────────
echo ""
echo -e "${GREEN}✅ CoreIDS sensor installed and started!${NC}"
echo ""
echo "  Instance:  ${DEVICE_ID}"
echo "  Check status:"
echo "    sudo systemctl status ${SERVICE_NAME}"
echo ""
echo "  View live logs:"
echo "    sudo journalctl -u ${SERVICE_NAME} -f"
echo ""
echo "  Verify in dashboard:"
echo "    Devices page → click 'Test' on this sensor"
echo ""

STATUS=$(systemctl is-active "$SERVICE_NAME" 2>/dev/null || echo "unknown")
if [[ "$STATUS" == "active" ]]; then
  echo -e "  ${GREEN}✓ Service is running${NC}"
else
  echo -e "  ${RED}✗ Service failed to start${NC}"
  echo "  Run: journalctl -u ${SERVICE_NAME} -n 50"
  echo ""
  echo -e "${CYAN}═══════════════════════════════════════${NC}"
  exit 1
fi

# ── Wait for cloud connection ────────────────────────────────
if [[ -n "$DEVICE_ID" && -n "$API_KEY" && -n "$SERVER" ]] && command -v curl &>/dev/null; then
  echo ""
  echo -e "  ${CYAN}Waiting for cloud connection...${NC}"
  URL="${SERVER}/api/v1/device/${DEVICE_ID}/status?api_key=${API_KEY}"
  MAX_RETRIES=18  # ~90 seconds (18 * 5s)
  SUCCESS=false
  for i in $(seq 1 $MAX_RETRIES); do
    RESP=$(curl -sf "$URL" 2>/dev/null)
    if echo "$RESP" | grep -q '"online":true'; then
      LAST=$(echo "$RESP" | grep -o '"last_seen_human":"[^"]*"' | cut -d'"' -f4)
      echo -e "  ${GREEN}✓ Connected! Last seen: ${LAST}${NC}"
      SUCCESS=true
      break
    fi
    printf "  ."
    sleep 5
  done
  if [[ "$SUCCESS" == "false" ]]; then
    echo ""
    echo -e "  ${YELLOW}(daemon still connecting — heartbeats every 30s, check journalctl -u coreids.service -n 20)${NC}"
  fi
fi
echo ""
echo -e "${CYAN}═══════════════════════════════════════${NC}"
